version: '3.8'

services:
  postgres:
    image: postgres:15  # Use the latest stable version
    container_name: my_postgres_cutm
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"  # Map PostgreSQL default port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage

  redis:
    image: redis:latest
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres_data:
    driver: local
